import { LayoutSide } from "@/components/organisms";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight

import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Head>
				<link
					rel='stylesheet'
					href='https://unpkg.com/@douyinfe/semi-ui@2.27.0/dist/css/semi.css'
				/>
			</Head>
			<body className={inter.className}>
				<LayoutSide>{children}</LayoutSide>
			</body>
		</html>
	);
}
